import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL);
const scores = await sql`select count(*) c, max(updated_at) latest from match_scores`;
const subs = await sql`select preferences, count(*) c from subscriptions group by preferences order by c desc`;
const total = await sql`select count(*) c from subscriptions`;
const recent = await sql`select email, preferences, created_at from subscriptions order by created_at desc limit 5`;
console.log('match_scores:', JSON.stringify(scores[0]));
console.log('订阅分层:', JSON.stringify(subs));
console.log('总订阅:', total[0].c);
console.log('最近5个注册:');
recent.forEach(r=>console.log('  ', r.email.replace(/(.{3}).*(@.*)/,'$1***$2'), r.preferences, r.created_at));
